server:
  servlet:
    context-path: /reality
  port: 8080
app:
  host: "${APP_HOST}"
email:
  host: "${EMAIL_HOST}"
  port: "${EMAIL_PORT}"
  login: "${EMAIL_LOGIN}"
  password: "${EMAIL_PASSWORD}"
  necessaryCount: "${EMAIL_NECESSARY_COUNT:50000}"
telegram:
  bot:
    name: "reality-bot"
    token: "${TG_BOT_TOKEN}"
  chat:
    id: "${TG_CHAT_ID}"